theme: jekyll-theme-slate
title: Finding By Counting
description: Localizing at Decimeter Level in Indoor Public Spaces 
description: [Home](#indoor-localization)  [About](#key-features)  [Releases](#releases)  [Papers](#papers)  [Contact-Us](#contact-us)

