theme: jekyll-theme-slate
title: Finding By Counting
description: Localizing at Decimeter Level in Indoor Public Spaces
![logo](https://github.com/blelocalization/blelocalization.github.io/blob/master/gitpageImage1.jpg)
