
title: Finding By Counting
description: Localizing at Decimeter Level in Indoor Public Spaces bkbk

picture:

  source: gitpageImage1.jpg 

  output: generated

  markup: picture

  presets:

    # Full width pictures

    default:

      ppi: [1, 1.5]

      attr:

        class: blog-full

        itemprop: image

      source_lrg:

        media: "(min-width: 40em)"

        width: 700

      source_med:

        media: "(min-width: 30em)"

        width: 450

      source_default:

        width: 350

        height: 200
