theme: jekyll-theme-slate
title: Finding By Counting
description: Localizing at Decimeter Level in Indoor Public Spaces 
url : https://blelocalization.github.io
author-email : de5@illinois.com
author: Subham De
