theme: jekyll-theme-slate
title: Finding By Counting
description: Localizing at Decimeter Level in Indoor Public Spaces 
navbar :
  archive :

    enabled : true

  categories :

    enabled : true

  tags :

    enabled : true

  github_projects :

    enabled : false

  social_links :

    enabled : false

  external_links :

    enabled : false
